# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{timeframe}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andy Rossmeissl", "Seamus Abshere", "Derek Kastner"]
  s.date = %q{2010-07-16}
  s.description = %q{A Ruby class for describing and interacting with timeframes.}
  s.email = %q{andy@rossmeissl.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/timeframe.rb",
     "lib/timeframe/ykk.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/timeframe_spec.rb",
     "timeframe.gemspec"
  ]
  s.homepage = %q{http://github.com/rossmeissl/timeframe}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Date intervals}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/timeframe_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.8"])
      s.add_runtime_dependency(%q<to_json_fix>, [">= 0.0.1"])
      s.add_runtime_dependency(%q<andand>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<activesupport>, [">= 2.3.8"])
      s.add_dependency(%q<to_json_fix>, [">= 0.0.1"])
      s.add_dependency(%q<andand>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<activesupport>, [">= 2.3.8"])
    s.add_dependency(%q<to_json_fix>, [">= 0.0.1"])
    s.add_dependency(%q<andand>, [">= 0"])
  end
end

